### ISSUE TITLE
Only backup data?

### ISSUE THREAD

**Issue by nodiscc** [karan/RedditAgain#10]
Hi, thanks for your work on this.
This is related to https://github.com/karan/RedditAgain/issues/2; is there a way to just backup my data locally (subscriptions, comments, submissions, multireddits) to CSV or json, without moving it to a new account? 

I tried entering a blank username/password at  the _new account_ prompt, but the script aborts.

**Comment by dClauzel** [comment]
Easy. Just remove the instructions which delete the submissions and contents, and also delete the part creating the new account:
- delete l70: `com.edit('.')`
- delete l99:  `sub.edit('.')`
- delete from l106 to the end

**Comment by nodiscc** [comment]
Thanks @dClauzel :+1:
