### ISSUE TITLE
Editing content out of comments vs. deleting

### ISSUE THREAD

**Issue by engstrom** [karan/RedditAgain#7]
According to [this post](http://www.reddit.com/r/blog/comments/1dhw2j/reddits_privacy_policy_has_been_rewritten_from/c9qgosg) editing a comment to remove its content is better than simply deleting it. I understand this may be outside the scope of RedditAgain but I just thought I'd point this out in case it was a feature you were interested in adding. It might be nice to have an option to edit out all content en masse vs. simply deleting if a user is worried about privacy.

**Comment by karan** [comment]
It's not too hard to implement, but I have no time in my hand. If I do find time, I'll change it. PR welcome.
